/* Generated by Parser/pgen */

#include "pgenheaders.h"
#include "grammar.h"
PyAPI_DATA(grammar) _PyParser_Grammar;
static arc arcs_0_0[3] = {
    {2, 1},
    {3, 1},
    {4, 2},
};
static arc arcs_0_1[1] = {
    {0, 1},
};
static arc arcs_0_2[1] = {
    {2, 1},
};
static state states_0[3] = {
    {3, arcs_0_0},
    {1, arcs_0_1},
    {1, arcs_0_2},
};
static arc arcs_1_0[3] = {
    {2, 0},
    {6, 0},
    {7, 1},
};
static arc arcs_1_1[1] = {
    {0, 1},
};
static state states_1[2] = {
    {3, arcs_1_0},
    {1, arcs_1_1},
};
static arc arcs_2_0[1] = {
    {9, 1},
};
static arc arcs_2_1[2] = {
    {2, 1},
    {7, 2},
};
static arc arcs_2_2[1] = {
    {0, 2},
};
static state states_2[3] = {
    {1, arcs_2_0},
    {2, arcs_2_1},
    {1, arcs_2_2},
};
static arc arcs_3_0[1] = {
    {11, 1},
};
static arc arcs_3_1[1] = {
    {12, 2},
};
static arc arcs_3_2[2] = {
    {13, 3},
    {2, 4},
};
static arc arcs_3_3[2] = {
    {14, 5},
    {15, 6},
};
static arc arcs_3_4[1] = {
    {0, 4},
};
static arc arcs_3_5[1] = {
    {15, 6},
};
static arc arcs_3_6[1] = {
    {2, 4},
};
static state states_3[7] = {
    {1, arcs_3_0},
    {1, arcs_3_1},
    {2, arcs_3_2},
    {2, arcs_3_3},
    {1, arcs_3_4},
    {1, arcs_3_5},
    {1, arcs_3_6},
};
static arc arcs_4_0[1] = {
    {10, 1},
};
static arc arcs_4_1[2] = {
    {10, 1},
    {0, 1},
};
static state states_4[2] = {
    {1, arcs_4_0},
    {2, arcs_4_1},
};
static arc arcs_5_0[1] = {
    {16, 1},
};
static arc arcs_5_1[3] = {
    {18, 2},
    {19, 2},
    {20, 2},
};
static arc arcs_5_2[1] = {
    {0, 2},
};
static state states_5[3] = {
    {1, arcs_5_0},
    {3, arcs_5_1},
    {1, arcs_5_2},
};
static arc arcs_6_0[1] = {
    {21, 1},
};
static arc arcs_6_1[1] = {
    {19, 2},
};
static arc arcs_6_2[1] = {
    {0, 2},
};
static state states_6[3] = {
    {1, arcs_6_0},
    {1, arcs_6_1},
    {1, arcs_6_2},
};
static arc arcs_7_0[1] = {
    {22, 1},
};
static arc arcs_7_1[1] = {
    {23, 2},
};
static arc arcs_7_2[1] = {
    {24, 3},
};
static arc arcs_7_3[2] = {
    {25, 4},
    {27, 5},
};
static arc arcs_7_4[1] = {
    {26, 6},
};
static arc arcs_7_5[1] = {
    {28, 7},
};
static arc arcs_7_6[1] = {
    {27, 5},
};
static arc arcs_7_7[1] = {
    {0, 7},
};
static state states_7[8] = {
    {1, arcs_7_0},
    {1, arcs_7_1},
    {1, arcs_7_2},
    {2, arcs_7_3},
    {1, arcs_7_4},
    {1, arcs_7_5},
    {1, arcs_7_6},
    {1, arcs_7_7},
};
static arc arcs_8_0[1] = {
    {13, 1},
};
static arc arcs_8_1[2] = {
    {29, 2},
    {15, 3},
};
static arc arcs_8_2[1] = {
    {15, 3},
};
static arc arcs_8_3[1] = {
    {0, 3},
};
static state states_8[4] = {
    {1, arcs_8_0},
    {2, arcs_8_1},
    {1, arcs_8_2},
    {1, arcs_8_3},
};
static arc arcs_9_0[3] = {
    {30, 1},
    {33, 2},
    {34, 3},
};
static arc arcs_9_1[3] = {
    {31, 4},
    {32, 5},
    {0, 1},
};
static arc arcs_9_2[3] = {
    {30, 6},
    {32, 7},
    {0, 2},
};
static arc arcs_9_3[1] = {
    {30, 8},
};
static arc arcs_9_4[1] = {
    {26, 9},
};
static arc arcs_9_5[4] = {
    {30, 10},
    {33, 11},
    {34, 3},
    {0, 5},
};
static arc arcs_9_6[2] = {
    {32, 7},
    {0, 6},
};
static arc arcs_9_7[3] = {
    {30, 12},
    {34, 3},
    {0, 7},
};
static arc arcs_9_8[2] = {
    {32, 13},
    {0, 8},
};
static arc arcs_9_9[2] = {
    {32, 5},
    {0, 9},
};
static arc arcs_9_10[3] = {
    {32, 5},
    {31, 4},
    {0, 10},
};
static arc arcs_9_11[3] = {
    {30, 14},
    {32, 15},
    {0, 11},
};
static arc arcs_9_12[3] = {
    {32, 7},
    {31, 16},
    {0, 12},
};
static arc arcs_9_13[1] = {
    {0, 13},
};
static arc arcs_9_14[2] = {
    {32, 15},
    {0, 14},
};
static arc arcs_9_15[3] = {
    {30, 17},
    {34, 3},
    {0, 15},
};
static arc arcs_9_16[1] = {
    {26, 6},
};
static arc arcs_9_17[3] = {
    {32, 15},
    {31, 18},
    {0, 17},
};
static arc arcs_9_18[1] = {
    {26, 14},
};
static state states_9[19] = {
    {3, arcs_9_0},
    {3, arcs_9_1},
    {3, arcs_9_2},
    {1, arcs_9_3},
    {1, arcs_9_4},
    {4, arcs_9_5},
    {2, arcs_9_6},
    {3, arcs_9_7},
    {2, arcs_9_8},
    {2, arcs_9_9},
    {3, arcs_9_10},
    {3, arcs_9_11},
    {3, arcs_9_12},
    {1, arcs_9_13},
    {2, arcs_9_14},
    {3, arcs_9_15},
    {1, arcs_9_16},
    {3, arcs_9_17},
    {1, arcs_9_18},
};
static arc arcs_10_0[1] = {
    {23, 1},
};
static arc arcs_10_1[2] = {
    {27, 2},
    {0, 1},
};
static arc arcs_10_2[1] = {
    {26, 3},
};
static arc arcs_10_3[1] = {
    {0, 3},
};
static state states_10[4] = {
    {1, arcs_10_0},
    {2, arcs_10_1},
    {1, arcs_10_2},
    {1, arcs_10_3},
};
static arc arcs_11_0[3] = {
    {36, 1},
    {33, 2},
    {34, 3},
};
static arc arcs_11_1[3] = {
    {31, 4},
    {32, 5},
    {0, 1},
};
static arc arcs_11_2[3] = {
    {36, 6},
    {32, 7},
    {0, 2},
};
static arc arcs_11_3[1] = {
    {36, 8},
};
static arc arcs_11_4[1] = {
    {26, 9},
};
static arc arcs_11_5[4] = {
    {36, 10},
    {33, 11},
    {34, 3},
    {0, 5},
};
static arc arcs_11_6[2] = {
    {32, 7},
    {0, 6},
};
static arc arcs_11_7[3] = {
    {36, 12},
    {34, 3},
    {0, 7},
};
static arc arcs_11_8[2] = {
    {32, 13},
    {0, 8},
};
static arc arcs_11_9[2] = {
    {32, 5},
    {0, 9},
};
static arc arcs_11_10[3] = {
    {32, 5},
    {31, 4},
    {0, 10},
};
static arc arcs_11_11[3] = {
    {36, 14},
    {32, 15},
    {0, 11},
};
static arc arcs_11_12[3] = {
    {32, 7},
    {31, 16},
    {0, 12},
};
static arc arcs_11_13[1] = {
    {0, 13},
};
static arc arcs_11_14[2] = {
    {32, 15},
    {0, 14},
};
static arc arcs_11_15[3] = {
    {36, 17},
    {34, 3},
    {0, 15},
};
static arc arcs_11_16[1] = {
    {26, 6},
};
static arc arcs_11_17[3] = {
    {32, 15},
    {31, 18},
    {0, 17},
};
static arc arcs_11_18[1] = {
    {26, 14},
};
static state states_11[19] = {
    {3, arcs_11_0},
    {3, arcs_11_1},
    {3, arcs_11_2},
    {1, arcs_11_3},
    {1, arcs_11_4},
    {4, arcs_11_5},
    {2, arcs_11_6},
    {3, arcs_11_7},
    {2, arcs_11_8},
    {2, arcs_11_9},
    {3, arcs_11_10},
    {3, arcs_11_11},
    {3, arcs_11_12},
    {1, arcs_11_13},
    {2, arcs_11_14},
    {3, arcs_11_15},
    {1, arcs_11_16},
    {3, arcs_11_17},
    {1, arcs_11_18},
};
static arc arcs_12_0[1] = {
    {23, 1},
};
static arc arcs_12_1[1] = {
    {0, 1},
};
static state states_12[2] = {
    {1, arcs_12_0},
    {1, arcs_12_1},
};
static arc arcs_13_0[2] = {
    {3, 1},
    {4, 1},
};
static arc arcs_13_1[1] = {
    {0, 1},
};
static state states_13[2] = {
    {2, arcs_13_0},
    {1, arcs_13_1},
};
static arc arcs_14_0[1] = {
    {37, 1},
};
static arc arcs_14_1[2] = {
    {38, 2},
    {2, 3},
};
static arc arcs_14_2[2] = {
    {37, 1},
    {2, 3},
};
static arc arcs_14_3[1] = {
    {0, 3},
};
static state states_14[4] = {
    {1, arcs_14_0},
    {2, arcs_14_1},
    {2, arcs_14_2},
    {1, arcs_14_3},
};
static arc arcs_15_0[8] = {
    {39, 1},
    {40, 1},
    {41, 1},
    {42, 1},
    {43, 1},
    {44, 1},
    {45, 1},
    {46, 1},
};
static arc arcs_15_1[1] = {
    {0, 1},
};
static state states_15[2] = {
    {8, arcs_15_0},
    {1, arcs_15_1},
};
static arc arcs_16_0[1] = {
    {47, 1},
};
static arc arcs_16_1[3] = {
    {48, 2},
    {31, 3},
    {0, 1},
};
static arc arcs_16_2[2] = {
    {49, 4},
    {9, 4},
};
static arc arcs_16_3[2] = {
    {49, 5},
    {47, 5},
};
static arc arcs_16_4[1] = {
    {0, 4},
};
static arc arcs_16_5[2] = {
    {31, 3},
    {0, 5},
};
static state states_16[6] = {
    {1, arcs_16_0},
    {3, arcs_16_1},
    {2, arcs_16_2},
    {2, arcs_16_3},
    {1, arcs_16_4},
    {2, arcs_16_5},
};
static arc arcs_17_0[2] = {
    {26, 1},
    {50, 1},
};
static arc arcs_17_1[2] = {
    {32, 2},
    {0, 1},
};
static arc arcs_17_2[3] = {
    {26, 1},
    {50, 1},
    {0, 2},
};
static state states_17[3] = {
    {2, arcs_17_0},
    {2, arcs_17_1},
    {3, arcs_17_2},
};
static arc arcs_18_0[13] = {
    {51, 1},
    {52, 1},
    {53, 1},
    {54, 1},
    {55, 1},
    {56, 1},
    {57, 1},
    {58, 1},
    {59, 1},
    {60, 1},
    {61, 1},
    {62, 1},
    {63, 1},
};
static arc arcs_18_1[1] = {
    {0, 1},
};
static state states_18[2] = {
    {13, arcs_18_0},
    {1, arcs_18_1},
};
static arc arcs_19_0[1] = {
    {64, 1},
};
static arc arcs_19_1[1] = {
    {65, 2},
};
static arc arcs_19_2[1] = {
    {0, 2},
};
static state states_19[3] = {
    {1, arcs_19_0},
    {1, arcs_19_1},
    {1, arcs_19_2},
};
static arc arcs_20_0[1] = {
    {66, 1},
};
static arc arcs_20_1[1] = {
    {0, 1},
};
static state states_20[2] = {
    {1, arcs_20_0},
    {1, arcs_20_1},
};
static arc arcs_21_0[5] = {
    {67, 1},
    {68, 1},
    {69, 1},
    {70, 1},
    {71, 1},
};
static arc arcs_21_1[1] = {
    {0, 1},
};
static state states_21[2] = {
    {5, arcs_21_0},
    {1, arcs_21_1},
};
static arc arcs_22_0[1] = {
    {72, 1},
};
static arc arcs_22_1[1] = {
    {0, 1},
};
static state states_22[2] = {
    {1, arcs_22_0},
    {1, arcs_22_1},
};
static arc arcs_23_0[1] = {
    {73, 1},
};
static arc arcs_23_1[1] = {
    {0, 1},
};
static state states_23[2] = {
    {1, arcs_23_0},
    {1, arcs_23_1},
};
static arc arcs_24_0[1] = {
    {74, 1},
};
static arc arcs_24_1[2] = {
    {9, 2},
    {0, 1},
};
static arc arcs_24_2[1] = {
    {0, 2},
};
static state states_24[3] = {
    {1, arcs_24_0},
    {2, arcs_24_1},
    {1, arcs_24_2},
};
static arc arcs_25_0[1] = {
    {49, 1},
};
static arc arcs_25_1[1] = {
    {0, 1},
};
static state states_25[2] = {
    {1, arcs_25_0},
    {1, arcs_25_1},
};
static arc arcs_26_0[1] = {
    {75, 1},
};
static arc arcs_26_1[2] = {
    {26, 2},
    {0, 1},
};
static arc arcs_26_2[2] = {
    {76, 3},
    {0, 2},
};
static arc arcs_26_3[1] = {
    {26, 4},
};
static arc arcs_26_4[1] = {
    {0, 4},
};
static state states_26[5] = {
    {1, arcs_26_0},
    {2, arcs_26_1},
    {2, arcs_26_2},
    {1, arcs_26_3},
    {1, arcs_26_4},
};
static arc arcs_27_0[2] = {
    {77, 1},
    {78, 1},
};
static arc arcs_27_1[1] = {
    {0, 1},
};
static state states_27[2] = {
    {2, arcs_27_0},
    {1, arcs_27_1},
};
static arc arcs_28_0[1] = {
    {79, 1},
};
static arc arcs_28_1[1] = {
    {80, 2},
};
static arc arcs_28_2[1] = {
    {0, 2},
};
static state states_28[3] = {
    {1, arcs_28_0},
    {1, arcs_28_1},
    {1, arcs_28_2},
};
static arc arcs_29_0[1] = {
    {76, 1},
};
static arc arcs_29_1[3] = {
    {81, 2},
    {82, 2},
    {12, 3},
};
static arc arcs_29_2[4] = {
    {81, 2},
    {82, 2},
    {12, 3},
    {79, 4},
};
static arc arcs_29_3[1] = {
    {79, 4},
};
static arc arcs_29_4[3] = {
    {33, 5},
    {13, 6},
    {83, 5},
};
static arc arcs_29_5[1] = {
    {0, 5},
};
static arc arcs_29_6[1] = {
    {83, 7},
};
static arc arcs_29_7[1] = {
    {15, 5},
};
static state states_29[8] = {
    {1, arcs_29_0},
    {3, arcs_29_1},
    {4, arcs_29_2},
    {1, arcs_29_3},
    {3, arcs_29_4},
    {1, arcs_29_5},
    {1, arcs_29_6},
    {1, arcs_29_7},
};
static arc arcs_30_0[1] = {
    {23, 1},
};
static arc arcs_30_1[2] = {
    {85, 2},
    {0, 1},
};
static arc arcs_30_2[1] = {
    {23, 3},
};
static arc arcs_30_3[1] = {
    {0, 3},
};
static state states_30[4] = {
    {1, arcs_30_0},
    {2, arcs_30_1},
    {1, arcs_30_2},
    {1, arcs_30_3},
};
static arc arcs_31_0[1] = {
    {12, 1},
};
static arc arcs_31_1[2] = {
    {85, 2},
    {0, 1},
};
static arc arcs_31_2[1] = {
    {23, 3},
};
static arc arcs_31_3[1] = {
    {0, 3},
};
static state states_31[4] = {
    {1, arcs_31_0},
    {2, arcs_31_1},
    {1, arcs_31_2},
    {1, arcs_31_3},
};
static arc arcs_32_0[1] = {
    {84, 1},
};
static arc arcs_32_1[2] = {
    {32, 2},
    {0, 1},
};
static arc arcs_32_2[2] = {
    {84, 1},
    {0, 2},
};
static state states_32[3] = {
    {1, arcs_32_0},
    {2, arcs_32_1},
    {2, arcs_32_2},
};
static arc arcs_33_0[1] = {
    {86, 1},
};
static arc arcs_33_1[2] = {
    {32, 0},
    {0, 1},
};
static state states_33[2] = {
    {1, arcs_33_0},
    {2, arcs_33_1},
};
static arc arcs_34_0[1] = {
    {23, 1},
};
static arc arcs_34_1[2] = {
    {81, 0},
    {0, 1},
};
static state states_34[2] = {
    {1, arcs_34_0},
    {2, arcs_34_1},
};
static arc arcs_35_0[1] = {
    {87, 1},
};
static arc arcs_35_1[1] = {
    {23, 2},
};
static arc arcs_35_2[2] = {
    {32, 1},
    {0, 2},
};
static state states_35[3] = {
    {1, arcs_35_0},
    {1, arcs_35_1},
    {2, arcs_35_2},
};
static arc arcs_36_0[1] = {
    {88, 1},
};
static arc arcs_36_1[1] = {
    {23, 2},
};
static arc arcs_36_2[2] = {
    {32, 1},
    {0, 2},
};
static state states_36[3] = {
    {1, arcs_36_0},
    {1, arcs_36_1},
    {2, arcs_36_2},
};
static arc arcs_37_0[1] = {
    {89, 1},
};
static arc arcs_37_1[1] = {
    {26, 2},
};
static arc arcs_37_2[2] = {
    {32, 3},
    {0, 2},
};
static arc arcs_37_3[1] = {
    {26, 4},
};
static arc arcs_37_4[1] = {
    {0, 4},
};
static state states_37[5] = {
    {1, arcs_37_0},
    {1, arcs_37_1},
    {2, arcs_37_2},
    {1, arcs_37_3},
    {1, arcs_37_4},
};
static arc arcs_38_0[9] = {
    {90, 1},
    {91, 1},
    {92, 1},
    {93, 1},
    {94, 1},
    {19, 1},
    {18, 1},
    {17, 1},
    {95, 1},
};
static arc arcs_38_1[1] = {
    {0, 1},
};
static state states_38[2] = {
    {9, arcs_38_0},
    {1, arcs_38_1},
};
static arc arcs_39_0[1] = {
    {21, 1},
};
static arc arcs_39_1[3] = {
    {19, 2},
    {94, 2},
    {92, 2},
};
static arc arcs_39_2[1] = {
    {0, 2},
};
static state states_39[3] = {
    {1, arcs_39_0},
    {3, arcs_39_1},
    {1, arcs_39_2},
};
static arc arcs_40_0[1] = {
    {96, 1},
};
static arc arcs_40_1[1] = {
    {26, 2},
};
static arc arcs_40_2[1] = {
    {27, 3},
};
static arc arcs_40_3[1] = {
    {28, 4},
};
static arc arcs_40_4[6] = {
    {97, 1},
    {98, 1},
    {99, 5},
    {101, 6},
    {102, 6},
    {0, 4},
};
static arc arcs_40_5[1] = {
    {100, 7},
};
static arc arcs_40_6[1] = {
    {27, 8},
};
static arc arcs_40_7[2] = {
    {99, 1},
    {27, 8},
};
static arc arcs_40_8[1] = {
    {28, 9},
};
static arc arcs_40_9[1] = {
    {0, 9},
};
static state states_40[10] = {
    {1, arcs_40_0},
    {1, arcs_40_1},
    {1, arcs_40_2},
    {1, arcs_40_3},
    {6, arcs_40_4},
    {1, arcs_40_5},
    {1, arcs_40_6},
    {2, arcs_40_7},
    {1, arcs_40_8},
    {1, arcs_40_9},
};
static arc arcs_41_0[1] = {
    {103, 1},
};
static arc arcs_41_1[1] = {
    {26, 2},
};
static arc arcs_41_2[1] = {
    {27, 3},
};
static arc arcs_41_3[1] = {
    {28, 4},
};
static arc arcs_41_4[2] = {
    {104, 5},
    {0, 4},
};
static arc arcs_41_5[1] = {
    {27, 6},
};
static arc arcs_41_6[1] = {
    {28, 7},
};
static arc arcs_41_7[1] = {
    {0, 7},
};
static state states_41[8] = {
    {1, arcs_41_0},
    {1, arcs_41_1},
    {1, arcs_41_2},
    {1, arcs_41_3},
    {2, arcs_41_4},
    {1, arcs_41_5},
    {1, arcs_41_6},
    {1, arcs_41_7},
};
static arc arcs_42_0[1] = {
    {105, 1},
};
static arc arcs_42_1[1] = {
    {65, 2},
};
static arc arcs_42_2[1] = {
    {106, 3},
};
static arc arcs_42_3[1] = {
    {9, 4},
};
static arc arcs_42_4[1] = {
    {27, 5},
};
static arc arcs_42_5[1] = {
    {28, 6},
};
static arc arcs_42_6[4] = {
    {101, 7},
    {102, 7},
    {99, 8},
    {0, 6},
};
static arc arcs_42_7[1] = {
    {27, 9},
};
static arc arcs_42_8[1] = {
    {100, 7},
};
static arc arcs_42_9[1] = {
    {28, 10},
};
static arc arcs_42_10[1] = {
    {0, 10},
};
static state states_42[11] = {
    {1, arcs_42_0},
    {1, arcs_42_1},
    {1, arcs_42_2},
    {1, arcs_42_3},
    {1, arcs_42_4},
    {1, arcs_42_5},
    {4, arcs_42_6},
    {1, arcs_42_7},
    {1, arcs_42_8},
    {1, arcs_42_9},
    {1, arcs_42_10},
};
static arc arcs_43_0[1] = {
    {107, 1},
};
static arc arcs_43_1[1] = {
    {27, 2},
};
static arc arcs_43_2[1] = {
    {28, 3},
};
static arc arcs_43_3[3] = {
    {108, 4},
    {109, 5},
    {110, 5},
};
static arc arcs_43_4[1] = {
    {27, 6},
};
static arc arcs_43_5[1] = {
    {27, 7},
};
static arc arcs_43_6[1] = {
    {28, 8},
};
static arc arcs_43_7[1] = {
    {28, 9},
};
static arc arcs_43_8[7] = {
    {108, 4},
    {101, 10},
    {102, 10},
    {99, 11},
    {109, 5},
    {110, 5},
    {0, 8},
};
static arc arcs_43_9[1] = {
    {0, 9},
};
static arc arcs_43_10[1] = {
    {27, 12},
};
static arc arcs_43_11[1] = {
    {100, 10},
};
static arc arcs_43_12[1] = {
    {28, 13},
};
static arc arcs_43_13[3] = {
    {109, 5},
    {110, 5},
    {0, 13},
};
static state states_43[14] = {
    {1, arcs_43_0},
    {1, arcs_43_1},
    {1, arcs_43_2},
    {3, arcs_43_3},
    {1, arcs_43_4},
    {1, arcs_43_5},
    {1, arcs_43_6},
    {1, arcs_43_7},
    {7, arcs_43_8},
    {1, arcs_43_9},
    {1, arcs_43_10},
    {1, arcs_43_11},
    {1, arcs_43_12},
    {3, arcs_43_13},
};
static arc arcs_44_0[1] = {
    {111, 1},
};
static arc arcs_44_1[1] = {
    {112, 2},
};
static arc arcs_44_2[2] = {
    {32, 1},
    {27, 3},
};
static arc arcs_44_3[1] = {
    {28, 4},
};
static arc arcs_44_4[1] = {
    {0, 4},
};
static state states_44[5] = {
    {1, arcs_44_0},
    {1, arcs_44_1},
    {2, arcs_44_2},
    {1, arcs_44_3},
    {1, arcs_44_4},
};
static arc arcs_45_0[1] = {
    {26, 1},
};
static arc arcs_45_1[2] = {
    {85, 2},
    {0, 1},
};
static arc arcs_45_2[1] = {
    {113, 3},
};
static arc arcs_45_3[1] = {
    {0, 3},
};
static state states_45[4] = {
    {1, arcs_45_0},
    {2, arcs_45_1},
    {1, arcs_45_2},
    {1, arcs_45_3},
};
static arc arcs_46_0[1] = {
    {114, 1},
};
static arc arcs_46_1[2] = {
    {26, 2},
    {0, 1},
};
static arc arcs_46_2[2] = {
    {85, 3},
    {0, 2},
};
static arc arcs_46_3[1] = {
    {23, 4},
};
static arc arcs_46_4[1] = {
    {0, 4},
};
static state states_46[5] = {
    {1, arcs_46_0},
    {2, arcs_46_1},
    {2, arcs_46_2},
    {1, arcs_46_3},
    {1, arcs_46_4},
};
static arc arcs_47_0[2] = {
    {3, 1},
    {2, 2},
};
static arc arcs_47_1[1] = {
    {0, 1},
};
static arc arcs_47_2[1] = {
    {115, 3},
};
static arc arcs_47_3[1] = {
    {6, 4},
};
static arc arcs_47_4[2] = {
    {6, 4},
    {116, 1},
};
static state states_47[5] = {
    {2, arcs_47_0},
    {1, arcs_47_1},
    {1, arcs_47_2},
    {1, arcs_47_3},
    {2, arcs_47_4},
};
static arc arcs_48_0[2] = {
    {117, 1},
    {118, 2},
};
static arc arcs_48_1[2] = {
    {96, 3},
    {0, 1},
};
static arc arcs_48_2[1] = {
    {0, 2},
};
static arc arcs_48_3[1] = {
    {117, 4},
};
static arc arcs_48_4[1] = {
    {104, 5},
};
static arc arcs_48_5[1] = {
    {26, 2},
};
static state states_48[6] = {
    {2, arcs_48_0},
    {2, arcs_48_1},
    {1, arcs_48_2},
    {1, arcs_48_3},
    {1, arcs_48_4},
    {1, arcs_48_5},
};
static arc arcs_49_0[2] = {
    {117, 1},
    {120, 1},
};
static arc arcs_49_1[1] = {
    {0, 1},
};
static state states_49[2] = {
    {2, arcs_49_0},
    {1, arcs_49_1},
};
static arc arcs_50_0[1] = {
    {121, 1},
};
static arc arcs_50_1[2] = {
    {35, 2},
    {27, 3},
};
static arc arcs_50_2[1] = {
    {27, 3},
};
static arc arcs_50_3[1] = {
    {26, 4},
};
static arc arcs_50_4[1] = {
    {0, 4},
};
static state states_50[5] = {
    {1, arcs_50_0},
    {2, arcs_50_1},
    {1, arcs_50_2},
    {1, arcs_50_3},
    {1, arcs_50_4},
};
static arc arcs_51_0[1] = {
    {121, 1},
};
static arc arcs_51_1[2] = {
    {35, 2},
    {27, 3},
};
static arc arcs_51_2[1] = {
    {27, 3},
};
static arc arcs_51_3[1] = {
    {119, 4},
};
static arc arcs_51_4[1] = {
    {0, 4},
};
static state states_51[5] = {
    {1, arcs_51_0},
    {2, arcs_51_1},
    {1, arcs_51_2},
    {1, arcs_51_3},
    {1, arcs_51_4},
};
static arc arcs_52_0[1] = {
    {122, 1},
};
static arc arcs_52_1[3] = {
    {123, 0},
    {124, 0},
    {0, 1},
};
static state states_52[2] = {
    {1, arcs_52_0},
    {3, arcs_52_1},
};
static arc arcs_53_0[1] = {
    {125, 1},
};
static arc arcs_53_1[3] = {
    {126, 0},
    {127, 0},
    {0, 1},
};
static state states_53[2] = {
    {1, arcs_53_0},
    {3, arcs_53_1},
};
static arc arcs_54_0[2] = {
    {128, 1},
    {129, 2},
};
static arc arcs_54_1[1] = {
    {125, 2},
};
static arc arcs_54_2[1] = {
    {0, 2},
};
static state states_54[3] = {
    {2, arcs_54_0},
    {1, arcs_54_1},
    {1, arcs_54_2},
};
static arc arcs_55_0[1] = {
    {113, 1},
};
static arc arcs_55_1[2] = {
    {130, 0},
    {0, 1},
};
static state states_55[2] = {
    {1, arcs_55_0},
    {2, arcs_55_1},
};
static arc arcs_56_0[13] = {
    {131, 1},
    {132, 1},
    {133, 1},
    {134, 1},
    {135, 1},
    {136, 1},
    {137, 1},
    {138, 1},
    {128, 2},
    {139, 3},
    {140, 1},
    {100, 4},
    {141, 1},
};
static arc arcs_56_1[1] = {
    {0, 1},
};
static arc arcs_56_2[1] = {
    {138, 1},
};
static arc arcs_56_3[2] = {
    {128, 1},
    {0, 3},
};
static arc arcs_56_4[2] = {
    {140, 1},
    {141, 1},
};
static state states_56[5] = {
    {13, arcs_56_0},
    {1, arcs_56_1},
    {1, arcs_56_2},
    {2, arcs_56_3},
    {2, arcs_56_4},
};
static arc arcs_57_0[1] = {
    {33, 1},
};
static arc arcs_57_1[1] = {
    {113, 2},
};
static arc arcs_57_2[1] = {
    {0, 2},
};
static state states_57[3] = {
    {1, arcs_57_0},
    {1, arcs_57_1},
    {1, arcs_57_2},
};
static arc arcs_58_0[1] = {
    {142, 1},
};
static arc arcs_58_1[2] = {
    {143, 0},
    {0, 1},
};
static state states_58[2] = {
    {1, arcs_58_0},
    {2, arcs_58_1},
};
static arc arcs_59_0[1] = {
    {144, 1},
};
static arc arcs_59_1[2] = {
    {145, 0},
    {0, 1},
};
static state states_59[2] = {
    {1, arcs_59_0},
    {2, arcs_59_1},
};
static arc arcs_60_0[1] = {
    {146, 1},
};
static arc arcs_60_1[2] = {
    {147, 0},
    {0, 1},
};
static state states_60[2] = {
    {1, arcs_60_0},
    {2, arcs_60_1},
};
static arc arcs_61_0[1] = {
    {148, 1},
};
static arc arcs_61_1[3] = {
    {149, 0},
    {150, 0},
    {0, 1},
};
static state states_61[2] = {
    {1, arcs_61_0},
    {3, arcs_61_1},
};
static arc arcs_62_0[1] = {
    {151, 1},
};
static arc arcs_62_1[3] = {
    {152, 0},
    {153, 0},
    {0, 1},
};
static state states_62[2] = {
    {1, arcs_62_0},
    {3, arcs_62_1},
};
static arc arcs_63_0[1] = {
    {154, 1},
};
static arc arcs_63_1[6] = {
    {33, 0},
    {11, 0},
    {155, 0},
    {156, 0},
    {157, 0},
    {0, 1},
};
static state states_63[2] = {
    {1, arcs_63_0},
    {6, arcs_63_1},
};
static arc arcs_64_0[4] = {
    {152, 1},
    {153, 1},
    {158, 1},
    {159, 2},
};
static arc arcs_64_1[1] = {
    {154, 2},
};
static arc arcs_64_2[1] = {
    {0, 2},
};
static state states_64[3] = {
    {4, arcs_64_0},
    {1, arcs_64_1},
    {1, arcs_64_2},
};
static arc arcs_65_0[1] = {
    {160, 1},
};
static arc arcs_65_1[2] = {
    {34, 2},
    {0, 1},
};
static arc arcs_65_2[1] = {
    {154, 3},
};
static arc arcs_65_3[1] = {
    {0, 3},
};
static state states_65[4] = {
    {1, arcs_65_0},
    {2, arcs_65_1},
    {1, arcs_65_2},
    {1, arcs_65_3},
};
static arc arcs_66_0[2] = {
    {161, 1},
    {162, 2},
};
static arc arcs_66_1[1] = {
    {162, 2},
};
static arc arcs_66_2[2] = {
    {163, 2},
    {0, 2},
};
static state states_66[3] = {
    {2, arcs_66_0},
    {1, arcs_66_1},
    {2, arcs_66_2},
};
static arc arcs_67_0[10] = {
    {13, 1},
    {165, 2},
    {167, 3},
    {23, 4},
    {170, 4},
    {171, 5},
    {82, 4},
    {172, 4},
    {173, 4},
    {174, 4},
};
static arc arcs_67_1[3] = {
    {49, 6},
    {164, 6},
    {15, 4},
};
static arc arcs_67_2[2] = {
    {164, 7},
    {166, 4},
};
static arc arcs_67_3[2] = {
    {168, 8},
    {169, 4},
};
static arc arcs_67_4[1] = {
    {0, 4},
};
static arc arcs_67_5[2] = {
    {171, 5},
    {0, 5},
};
static arc arcs_67_6[1] = {
    {15, 4},
};
static arc arcs_67_7[1] = {
    {166, 4},
};
static arc arcs_67_8[1] = {
    {169, 4},
};
static state states_67[9] = {
    {10, arcs_67_0},
    {3, arcs_67_1},
    {2, arcs_67_2},
    {2, arcs_67_3},
    {1, arcs_67_4},
    {2, arcs_67_5},
    {1, arcs_67_6},
    {1, arcs_67_7},
    {1, arcs_67_8},
};
static arc arcs_68_0[2] = {
    {26, 1},
    {50, 1},
};
static arc arcs_68_1[3] = {
    {175, 2},
    {32, 3},
    {0, 1},
};
static arc arcs_68_2[1] = {
    {0, 2},
};
static arc arcs_68_3[3] = {
    {26, 4},
    {50, 4},
    {0, 3},
};
static arc arcs_68_4[2] = {
    {32, 3},
    {0, 4},
};
static state states_68[5] = {
    {2, arcs_68_0},
    {3, arcs_68_1},
    {1, arcs_68_2},
    {3, arcs_68_3},
    {2, arcs_68_4},
};
static arc arcs_69_0[3] = {
    {13, 1},
    {165, 2},
    {81, 3},
};
static arc arcs_69_1[2] = {
    {14, 4},
    {15, 5},
};
static arc arcs_69_2[1] = {
    {176, 6},
};
static arc arcs_69_3[1] = {
    {23, 5},
};
static arc arcs_69_4[1] = {
    {15, 5},
};
static arc arcs_69_5[1] = {
    {0, 5},
};
static arc arcs_69_6[1] = {
    {166, 5},
};
static state states_69[7] = {
    {3, arcs_69_0},
    {2, arcs_69_1},
    {1, arcs_69_2},
    {1, arcs_69_3},
    {1, arcs_69_4},
    {1, arcs_69_5},
    {1, arcs_69_6},
};
static arc arcs_70_0[1] = {
    {177, 1},
};
static arc arcs_70_1[2] = {
    {32, 2},
    {0, 1},
};
static arc arcs_70_2[2] = {
    {177, 1},
    {0, 2},
};
static state states_70[3] = {
    {1, arcs_70_0},
    {2, arcs_70_1},
    {2, arcs_70_2},
};
static arc arcs_71_0[2] = {
    {26, 1},
    {27, 2},
};
static arc arcs_71_1[2] = {
    {27, 2},
    {0, 1},
};
static arc arcs_71_2[3] = {
    {26, 3},
    {178, 4},
    {0, 2},
};
static arc arcs_71_3[2] = {
    {178, 4},
    {0, 3},
};
static arc arcs_71_4[1] = {
    {0, 4},
};
static state states_71[5] = {
    {2, arcs_71_0},
    {2, arcs_71_1},
    {3, arcs_71_2},
    {2, arcs_71_3},
    {1, arcs_71_4},
};
static arc arcs_72_0[1] = {
    {27, 1},
};
static arc arcs_72_1[2] = {
    {26, 2},
    {0, 1},
};
static arc arcs_72_2[1] = {
    {0, 2},
};
static state states_72[3] = {
    {1, arcs_72_0},
    {2, arcs_72_1},
    {1, arcs_72_2},
};
static arc arcs_73_0[2] = {
    {113, 1},
    {50, 1},
};
static arc arcs_73_1[2] = {
    {32, 2},
    {0, 1},
};
static arc arcs_73_2[3] = {
    {113, 1},
    {50, 1},
    {0, 2},
};
static state states_73[3] = {
    {2, arcs_73_0},
    {2, arcs_73_1},
    {3, arcs_73_2},
};
static arc arcs_74_0[1] = {
    {26, 1},
};
static arc arcs_74_1[2] = {
    {32, 2},
    {0, 1},
};
static arc arcs_74_2[2] = {
    {26, 1},
    {0, 2},
};
static state states_74[3] = {
    {1, arcs_74_0},
    {2, arcs_74_1},
    {2, arcs_74_2},
};
static arc arcs_75_0[3] = {
    {26, 1},
    {34, 2},
    {50, 3},
};
static arc arcs_75_1[4] = {
    {27, 4},
    {175, 5},
    {32, 6},
    {0, 1},
};
static arc arcs_75_2[1] = {
    {113, 7},
};
static arc arcs_75_3[3] = {
    {175, 5},
    {32, 6},
    {0, 3},
};
static arc arcs_75_4[1] = {
    {26, 7},
};
static arc arcs_75_5[1] = {
    {0, 5},
};
static arc arcs_75_6[3] = {
    {26, 8},
    {50, 8},
    {0, 6},
};
static arc arcs_75_7[3] = {
    {175, 5},
    {32, 9},
    {0, 7},
};
static arc arcs_75_8[2] = {
    {32, 6},
    {0, 8},
};
static arc arcs_75_9[3] = {
    {26, 10},
    {34, 11},
    {0, 9},
};
static arc arcs_75_10[1] = {
    {27, 12},
};
static arc arcs_75_11[1] = {
    {113, 13},
};
static arc arcs_75_12[1] = {
    {26, 13},
};
static arc arcs_75_13[2] = {
    {32, 9},
    {0, 13},
};
static state states_75[14] = {
    {3, arcs_75_0},
    {4, arcs_75_1},
    {1, arcs_75_2},
    {3, arcs_75_3},
    {1, arcs_75_4},
    {1, arcs_75_5},
    {3, arcs_75_6},
    {3, arcs_75_7},
    {2, arcs_75_8},
    {3, arcs_75_9},
    {1, arcs_75_10},
    {1, arcs_75_11},
    {1, arcs_75_12},
    {2, arcs_75_13},
};
static arc arcs_76_0[1] = {
    {179, 1},
};
static arc arcs_76_1[1] = {
    {23, 2},
};
static arc arcs_76_2[2] = {
    {13, 3},
    {27, 4},
};
static arc arcs_76_3[2] = {
    {14, 5},
    {15, 6},
};
static arc arcs_76_4[1] = {
    {28, 7},
};
static arc arcs_76_5[1] = {
    {15, 6},
};
static arc arcs_76_6[1] = {
    {27, 4},
};
static arc arcs_76_7[1] = {
    {0, 7},
};
static state states_76[8] = {
    {1, arcs_76_0},
    {1, arcs_76_1},
    {2, arcs_76_2},
    {2, arcs_76_3},
    {1, arcs_76_4},
    {1, arcs_76_5},
    {1, arcs_76_6},
    {1, arcs_76_7},
};
static arc arcs_77_0[1] = {
    {180, 1},
};
static arc arcs_77_1[2] = {
    {32, 2},
    {0, 1},
};
static arc arcs_77_2[2] = {
    {180, 1},
    {0, 2},
};
static state states_77[3] = {
    {1, arcs_77_0},
    {2, arcs_77_1},
    {2, arcs_77_2},
};
static arc arcs_78_0[3] = {
    {26, 1},
    {34, 2},
    {33, 2},
};
static arc arcs_78_1[3] = {
    {175, 3},
    {31, 2},
    {0, 1},
};
static arc arcs_78_2[1] = {
    {26, 3},
};
static arc arcs_78_3[1] = {
    {0, 3},
};
static state states_78[4] = {
    {3, arcs_78_0},
    {3, arcs_78_1},
    {1, arcs_78_2},
    {1, arcs_78_3},
};
static arc arcs_79_0[2] = {
    {175, 1},
    {182, 1},
};
static arc arcs_79_1[1] = {
    {0, 1},
};
static state states_79[2] = {
    {2, arcs_79_0},
    {1, arcs_79_1},
};
static arc arcs_80_0[1] = {
    {105, 1},
};
static arc arcs_80_1[1] = {
    {65, 2},
};
static arc arcs_80_2[1] = {
    {138, 3},
};
static arc arcs_80_3[1] = {
    {117, 4},
};
static arc arcs_80_4[2] = {
    {181, 5},
    {0, 4},
};
static arc arcs_80_5[1] = {
    {0, 5},
};
static state states_80[6] = {
    {1, arcs_80_0},
    {1, arcs_80_1},
    {1, arcs_80_2},
    {1, arcs_80_3},
    {2, arcs_80_4},
    {1, arcs_80_5},
};
static arc arcs_81_0[1] = {
    {96, 1},
};
static arc arcs_81_1[1] = {
    {119, 2},
};
static arc arcs_81_2[2] = {
    {181, 3},
    {0, 2},
};
static arc arcs_81_3[1] = {
    {0, 3},
};
static state states_81[4] = {
    {1, arcs_81_0},
    {1, arcs_81_1},
    {2, arcs_81_2},
    {1, arcs_81_3},
};
static arc arcs_82_0[1] = {
    {23, 1},
};
static arc arcs_82_1[1] = {
    {0, 1},
};
static state states_82[2] = {
    {1, arcs_82_0},
    {1, arcs_82_1},
};
static arc arcs_83_0[1] = {
    {184, 1},
};
static arc arcs_83_1[2] = {
    {185, 2},
    {0, 1},
};
static arc arcs_83_2[1] = {
    {0, 2},
};
static state states_83[3] = {
    {1, arcs_83_0},
    {2, arcs_83_1},
    {1, arcs_83_2},
};
static arc arcs_84_0[2] = {
    {76, 1},
    {9, 2},
};
static arc arcs_84_1[1] = {
    {26, 2},
};
static arc arcs_84_2[1] = {
    {0, 2},
};
static state states_84[3] = {
    {2, arcs_84_0},
    {1, arcs_84_1},
    {1, arcs_84_2},
};
static arc arcs_85_0[1] = {
    {186, 1},
};
static arc arcs_85_1[1] = {
    {0, 1},
};
static state states_85[2] = {
    {1, arcs_85_0},
    {1, arcs_85_1},
};
static arc arcs_86_0[2] = {
    {187, 1},
    {188, 1},
};
static arc arcs_86_1[1] = {
    {0, 1},
};
static state states_86[2] = {
    {2, arcs_86_0},
    {1, arcs_86_1},
};
static arc arcs_87_0[2] = {
    {189, 1},
    {190, 1},
};
static arc arcs_87_1[1] = {
    {0, 1},
};
static state states_87[2] = {
    {2, arcs_87_0},
    {1, arcs_87_1},
};
static arc arcs_88_0[2] = {
    {191, 1},
    {192, 1},
};
static arc arcs_88_1[1] = {
    {0, 1},
};
static state states_88[2] = {
    {2, arcs_88_0},
    {1, arcs_88_1},
};
static arc arcs_89_0[2] = {
    {193, 1},
    {194, 1},
};
static arc arcs_89_1[1] = {
    {0, 1},
};
static state states_89[2] = {
    {2, arcs_89_0},
    {1, arcs_89_1},
};
static arc arcs_90_0[2] = {
    {195, 1},
    {196, 1},
};
static arc arcs_90_1[1] = {
    {0, 1},
};
static state states_90[2] = {
    {2, arcs_90_0},
    {1, arcs_90_1},
};
static arc arcs_91_0[2] = {
    {197, 1},
    {198, 1},
};
static arc arcs_91_1[1] = {
    {0, 1},
};
static state states_91[2] = {
    {2, arcs_91_0},
    {1, arcs_91_1},
};
static arc arcs_92_0[2] = {
    {199, 1},
    {200, 1},
};
static arc arcs_92_1[1] = {
    {0, 1},
};
static state states_92[2] = {
    {2, arcs_92_0},
    {1, arcs_92_1},
};
static arc arcs_93_0[2] = {
    {201, 1},
    {202, 1},
};
static arc arcs_93_1[1] = {
    {0, 1},
};
static state states_93[2] = {
    {2, arcs_93_0},
    {1, arcs_93_1},
};
static arc arcs_94_0[1] = {
    {203, 1},
};
static arc arcs_94_1[1] = {
    {0, 1},
};
static state states_94[2] = {
    {1, arcs_94_0},
    {1, arcs_94_1},
};
static arc arcs_95_0[2] = {
    {204, 1},
    {205, 1},
};
static arc arcs_95_1[1] = {
    {0, 1},
};
static state states_95[2] = {
    {2, arcs_95_0},
    {1, arcs_95_1},
};
static arc arcs_96_0[2] = {
    {206, 1},
    {207, 1},
};
static arc arcs_96_1[1] = {
    {0, 1},
};
static state states_96[2] = {
    {2, arcs_96_0},
    {1, arcs_96_1},
};
static arc arcs_97_0[2] = {
    {208, 1},
    {209, 1},
};
static arc arcs_97_1[1] = {
    {0, 1},
};
static state states_97[2] = {
    {2, arcs_97_0},
    {1, arcs_97_1},
};
static arc arcs_98_0[2] = {
    {210, 1},
    {211, 1},
};
static arc arcs_98_1[1] = {
    {0, 1},
};
static state states_98[2] = {
    {2, arcs_98_0},
    {1, arcs_98_1},
};
static arc arcs_99_0[1] = {
    {212, 1},
};
static arc arcs_99_1[1] = {
    {0, 1},
};
static state states_99[2] = {
    {1, arcs_99_0},
    {1, arcs_99_1},
};
static arc arcs_100_0[2] = {
    {213, 1},
    {214, 1},
};
static arc arcs_100_1[1] = {
    {0, 1},
};
static state states_100[2] = {
    {2, arcs_100_0},
    {1, arcs_100_1},
};
static arc arcs_101_0[2] = {
    {215, 1},
    {216, 1},
};
static arc arcs_101_1[1] = {
    {0, 1},
};
static state states_101[2] = {
    {2, arcs_101_0},
    {1, arcs_101_1},
};
static arc arcs_102_0[2] = {
    {217, 1},
    {218, 1},
};
static arc arcs_102_1[1] = {
    {0, 1},
};
static state states_102[2] = {
    {2, arcs_102_0},
    {1, arcs_102_1},
};
static arc arcs_103_0[2] = {
    {219, 1},
    {220, 1},
};
static arc arcs_103_1[1] = {
    {0, 1},
};
static state states_103[2] = {
    {2, arcs_103_0},
    {1, arcs_103_1},
};
static arc arcs_104_0[2] = {
    {221, 1},
    {99, 1},
};
static arc arcs_104_1[1] = {
    {0, 1},
};
static state states_104[2] = {
    {2, arcs_104_0},
    {1, arcs_104_1},
};
static arc arcs_105_0[2] = {
    {222, 1},
    {223, 1},
};
static arc arcs_105_1[1] = {
    {0, 1},
};
static state states_105[2] = {
    {2, arcs_105_0},
    {1, arcs_105_1},
};
static arc arcs_106_0[2] = {
    {224, 1},
    {225, 1},
};
static arc arcs_106_1[1] = {
    {0, 1},
};
static state states_106[2] = {
    {2, arcs_106_0},
    {1, arcs_106_1},
};
static arc arcs_107_0[2] = {
    {123, 1},
    {124, 1},
};
static arc arcs_107_1[1] = {
    {0, 1},
};
static state states_107[2] = {
    {2, arcs_107_0},
    {1, arcs_107_1},
};
static arc arcs_108_0[2] = {
    {101, 1},
    {102, 1},
};
static arc arcs_108_1[1] = {
    {0, 1},
};
static state states_108[2] = {
    {2, arcs_108_0},
    {1, arcs_108_1},
};
static arc arcs_109_0[2] = {
    {138, 1},
    {140, 1},
};
static arc arcs_109_1[1] = {
    {0, 1},
};
static state states_109[2] = {
    {2, arcs_109_0},
    {1, arcs_109_1},
};
static dfa dfas[110] = {
    {256, "single_input", 0, 3, states_0,
     "\004\050\240\000\002\000\000\000\000\000\004\000\010\000\000\000\001\000\000\103\242\174\000\374\377\377\363\077\003"},
    {257, "file_input", 0, 2, states_1,
     "\204\050\240\000\002\000\000\000\000\000\004\000\010\000\000\000\001\000\000\103\242\174\000\374\377\377\363\077\003"},
    {258, "eval_input", 0, 3, states_2,
     "\000\040\200\000\000\000\000\000\000\000\004\000\000\000\000\000\001\000\000\103\242\174\000\000\000\000\020\000\000"},
    {259, "decorator", 0, 7, states_3,
     "\000\010\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {260, "decorators", 0, 2, states_4,
     "\000\010\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {261, "decorated", 0, 3, states_5,
     "\000\010\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {262, "async_funcdef", 0, 3, states_6,
     "\000\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {263, "funcdef", 0, 8, states_7,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\004\000\000\000\000\000"},
    {264, "parameters", 0, 4, states_8,
     "\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {265, "typedargslist", 0, 19, states_9,
     "\000\000\200\000\006\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {266, "tfpdef", 0, 4, states_10,
     "\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {267, "varargslist", 0, 19, states_11,
     "\000\000\200\000\006\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {268, "vfpdef", 0, 2, states_12,
     "\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {269, "stmt", 0, 2, states_13,
     "\000\050\240\000\002\000\000\000\000\000\004\000\010\000\000\000\001\000\000\103\242\174\000\374\377\377\363\077\003"},
    {270, "simple_stmt", 0, 4, states_14,
     "\000\040\200\000\002\000\000\000\000\000\004\000\000\000\000\000\001\000\000\103\242\174\000\030\376\377\160\036\000"},
    {271, "small_stmt", 0, 2, states_15,
     "\000\040\200\000\002\000\000\000\000\000\004\000\000\000\000\000\001\000\000\103\242\174\000\030\376\377\160\036\000"},
    {272, "expr_stmt", 0, 6, states_16,
     "\000\040\200\000\002\000\000\000\000\000\004\000\000\000\000\000\001\000\000\103\242\174\000\000\000\000\020\000\000"},
    {273, "testlist_star_expr", 0, 3, states_17,
     "\000\040\200\000\002\000\000\000\000\000\004\000\000\000\000\000\001\000\000\103\242\174\000\000\000\000\020\000\000"},
    {274, "augassign", 0, 2, states_18,
     "\000\000\000\000\000\000\370\377\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {275, "del_stmt", 0, 3, states_19,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\200\001\000\000\000"},
    {276, "pass_stmt", 0, 2, states_20,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\030\000\000\000\000\000"},
    {277, "flow_stmt", 0, 2, states_21,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\176\006\140\000\000"},
    {278, "break_stmt", 0, 2, states_22,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\006\000\000\000\000"},
    {279, "continue_stmt", 0, 2, states_23,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\030\000\000\000\000"},
    {280, "return_stmt", 0, 3, states_24,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\140\000\000\000\000"},
    {281, "yield_stmt", 0, 2, states_25,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\140\000\000"},
    {282, "raise_stmt", 0, 5, states_26,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\006\000\000\000"},
    {283, "import_stmt", 0, 2, states_27,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\036\000"},
    {284, "import_name", 0, 3, states_28,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\006\000"},
    {285, "import_from", 0, 8, states_29,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\030\000"},
    {286, "import_as_name", 0, 4, states_30,
     "\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {287, "dotted_as_name", 0, 4, states_31,
     "\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {288, "import_as_names", 0, 3, states_32,
     "\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {289, "dotted_as_names", 0, 2, states_33,
     "\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {290, "dotted_name", 0, 2, states_34,
     "\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {291, "global_stmt", 0, 3, states_35,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\010\000\000\000"},
    {292, "nonlocal_stmt", 0, 3, states_36,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\060\000\000\000"},
    {293, "assert_stmt", 0, 5, states_37,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\300\000\000\000"},
    {294, "compound_stmt", 0, 2, states_38,
     "\000\010\040\000\000\000\000\000\000\000\000\000\010\000\000\000\000\000\000\000\000\000\000\344\001\000\203\041\003"},
    {295, "async_stmt", 0, 3, states_39,
     "\000\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {296, "if_stmt", 0, 10, states_40,
     "\000\000\000\000\000\000\000\000\000\000\000\000\010\000\000\000\000\000\000\000\000\000\000\000\000\000\000\040\000"},
    {297, "while_stmt", 0, 8, states_41,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\200\001\000"},
    {298, "for_stmt", 0, 11, states_42,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\200\001\000\000\000\000"},
    {299, "try_stmt", 0, 14, states_43,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\003"},
    {300, "with_stmt", 0, 5, states_44,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\003\000\000"},
    {301, "with_item", 0, 4, states_45,
     "\000\040\200\000\000\000\000\000\000\000\004\000\000\000\000\000\001\000\000\103\242\174\000\000\000\000\020\000\000"},
    {302, "except_clause", 0, 5, states_46,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\014\000\000"},
    {303, "suite", 0, 5, states_47,
     "\004\040\200\000\002\000\000\000\000\000\004\000\000\000\000\000\001\000\000\103\242\174\000\030\376\377\160\036\000"},
    {304, "test", 0, 6, states_48,
     "\000\040\200\000\000\000\000\000\000\000\004\000\000\000\000\000\001\000\000\103\242\174\000\000\000\000\020\000\000"},
    {305, "test_nocond", 0, 2, states_49,
     "\000\040\200\000\000\000\000\000\000\000\004\000\000\000\000\000\001\000\000\103\242\174\000\000\000\000\020\000\000"},
    {306, "lambdef", 0, 5, states_50,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\020\000\000"},
    {307, "lambdef_nocond", 0, 5, states_51,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\020\000\000"},
    {308, "or_test", 0, 2, states_52,
     "\000\040\200\000\000\000\000\000\000\000\004\000\000\000\000\000\001\000\000\103\242\174\000\000\000\000\000\000\000"},
    {309, "and_test", 0, 2, states_53,
     "\000\040\200\000\000\000\000\000\000\000\004\000\000\000\000\000\001\000\000\103\242\174\000\000\000\000\000\000\000"},
    {310, "not_test", 0, 3, states_54,
     "\000\040\200\000\000\000\000\000\000\000\004\000\000\000\000\000\001\000\000\103\242\174\000\000\000\000\000\000\000"},
    {311, "comparison", 0, 2, states_55,
     "\000\040\200\000\000\000\000\000\000\000\004\000\000\000\000\000\000\000\000\103\242\174\000\000\000\000\000\000\000"},
    {312, "comp_op", 0, 5, states_56,
     "\000\000\000\000\000\000\000\000\000\000\000\000\020\000\000\000\371\077\000\000\000\000\000\000\000\000\000\000\000"},
    {313, "star_expr", 0, 3, states_57,
     "\000\000\000\000\002\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {314, "expr", 0, 2, states_58,
     "\000\040\200\000\000\000\000\000\000\000\004\000\000\000\000\000\000\000\000\103\242\174\000\000\000\000\000\000\000"},
    {315, "xor_expr", 0, 2, states_59,
     "\000\040\200\000\000\000\000\000\000\000\004\000\000\000\000\000\000\000\000\103\242\174\000\000\000\000\000\000\000"},
    {316, "and_expr", 0, 2, states_60,
     "\000\040\200\000\000\000\000\000\000\000\004\000\000\000\000\000\000\000\000\103\242\174\000\000\000\000\000\000\000"},
    {317, "shift_expr", 0, 2, states_61,
     "\000\040\200\000\000\000\000\000\000\000\004\000\000\000\000\000\000\000\000\103\242\174\000\000\000\000\000\000\000"},
    {318, "arith_expr", 0, 2, states_62,
     "\000\040\200\000\000\000\000\000\000\000\004\000\000\000\000\000\000\000\000\103\242\174\000\000\000\000\000\000\000"},
    {319, "term", 0, 2, states_63,
     "\000\040\200\000\000\000\000\000\000\000\004\000\000\000\000\000\000\000\000\103\242\174\000\000\000\000\000\000\000"},
    {320, "factor", 0, 3, states_64,
     "\000\040\200\000\000\000\000\000\000\000\004\000\000\000\000\000\000\000\000\103\242\174\000\000\000\000\000\000\000"},
    {321, "power", 0, 4, states_65,
     "\000\040\200\000\000\000\000\000\000\000\004\000\000\000\000\000\000\000\000\000\242\174\000\000\000\000\000\000\000"},
    {322, "atom_expr", 0, 3, states_66,
     "\000\040\200\000\000\000\000\000\000\000\004\000\000\000\000\000\000\000\000\000\242\174\000\000\000\000\000\000\000"},
    {323, "atom", 0, 9, states_67,
     "\000\040\200\000\000\000\000\000\000\000\004\000\000\000\000\000\000\000\000\000\240\174\000\000\000\000\000\000\000"},
    {324, "testlist_comp", 0, 5, states_68,
     "\000\040\200\000\002\000\000\000\000\000\004\000\000\000\000\000\001\000\000\103\242\174\000\000\000\000\020\000\000"},
    {325, "trailer", 0, 7, states_69,
     "\000\040\000\000\000\000\000\000\000\000\002\000\000\000\000\000\000\000\000\000\040\000\000\000\000\000\000\000\000"},
    {326, "subscriptlist", 0, 3, states_70,
     "\000\040\200\010\000\000\000\000\000\000\004\000\000\000\000\000\001\000\000\103\242\174\000\000\000\000\020\000\000"},
    {327, "subscript", 0, 5, states_71,
     "\000\040\200\010\000\000\000\000\000\000\004\000\000\000\000\000\001\000\000\103\242\174\000\000\000\000\020\000\000"},
    {328, "sliceop", 0, 3, states_72,
     "\000\000\000\010\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {329, "exprlist", 0, 3, states_73,
     "\000\040\200\000\002\000\000\000\000\000\004\000\000\000\000\000\000\000\000\103\242\174\000\000\000\000\000\000\000"},
    {330, "testlist", 0, 3, states_74,
     "\000\040\200\000\000\000\000\000\000\000\004\000\000\000\000\000\001\000\000\103\242\174\000\000\000\000\020\000\000"},
    {331, "dictorsetmaker", 0, 14, states_75,
     "\000\040\200\000\006\000\000\000\000\000\004\000\000\000\000\000\001\000\000\103\242\174\000\000\000\000\020\000\000"},
    {332, "classdef", 0, 8, states_76,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\140\000\000\000\000\000"},
    {333, "arglist", 0, 3, states_77,
     "\000\040\200\000\006\000\000\000\000\000\004\000\000\000\000\000\001\000\000\103\242\174\000\000\000\000\020\000\000"},
    {334, "argument", 0, 4, states_78,
     "\000\040\200\000\006\000\000\000\000\000\004\000\000\000\000\000\001\000\000\103\242\174\000\000\000\000\020\000\000"},
    {335, "comp_iter", 0, 2, states_79,
     "\000\000\000\000\000\000\000\000\000\000\000\000\010\000\000\000\000\000\000\000\000\000\000\200\001\000\000\040\000"},
    {336, "comp_for", 0, 6, states_80,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\200\001\000\000\000\000"},
    {337, "comp_if", 0, 4, states_81,
     "\000\000\000\000\000\000\000\000\000\000\000\000\010\000\000\000\000\000\000\000\000\000\000\000\000\000\000\040\000"},
    {338, "encoding_decl", 0, 2, states_82,
     "\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {339, "yield_expr", 0, 3, states_83,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\140\000\000"},
    {340, "yield_arg", 0, 3, states_84,
     "\000\040\200\000\000\000\000\000\000\000\004\000\000\000\000\000\001\000\000\103\242\174\000\000\000\000\020\030\000"},
    {341, "pynata_def", 0, 2, states_85,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\004\000\000\000\000\000"},
    {342, "pynata_pass", 0, 2, states_86,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\030\000\000\000\000\000"},
    {343, "pynata_class", 0, 2, states_87,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\140\000\000\000\000\000"},
    {344, "pynata_for", 0, 2, states_88,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\200\001\000\000\000\000"},
    {345, "pynata_break", 0, 2, states_89,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\006\000\000\000\000"},
    {346, "pynata_continue", 0, 2, states_90,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\030\000\000\000\000"},
    {347, "pynata_return", 0, 2, states_91,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\140\000\000\000\000"},
    {348, "pynata_del", 0, 2, states_92,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\200\001\000\000\000"},
    {349, "pynata_raise", 0, 2, states_93,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\006\000\000\000"},
    {350, "pynata_global", 0, 2, states_94,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\010\000\000\000"},
    {351, "pynata_nonlocal", 0, 2, states_95,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\060\000\000\000"},
    {352, "pynata_assert", 0, 2, states_96,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\300\000\000\000"},
    {353, "pynata_with", 0, 2, states_97,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\003\000\000"},
    {354, "pynata_except", 0, 2, states_98,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\014\000\000"},
    {355, "pynata_lambda", 0, 2, states_99,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\020\000\000"},
    {356, "pynata_yield", 0, 2, states_100,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\140\000\000"},
    {357, "pynata_while", 0, 2, states_101,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\200\001\000"},
    {358, "pynata_import", 0, 2, states_102,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\006\000"},
    {359, "pynata_from", 0, 2, states_103,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\030\000"},
    {360, "pynata_if", 0, 2, states_104,
     "\000\000\000\000\000\000\000\000\000\000\000\000\010\000\000\000\000\000\000\000\000\000\000\000\000\000\000\040\000"},
    {361, "pynata_as", 0, 2, states_105,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\300\000"},
    {362, "pynata_try", 0, 2, states_106,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\003"},
    {363, "pynata_or", 0, 2, states_107,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\030\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {364, "pynata_else", 0, 2, states_108,
     "\000\000\000\000\000\000\000\000\000\000\000\000\140\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"},
    {365, "pynata_in", 0, 2, states_109,
     "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\024\000\000\000\000\000\000\000\000\000\000\000"},
};
static label labels[227] = {
    {0, "EMPTY"},
    {256, 0},
    {4, 0},
    {270, 0},
    {294, 0},
    {257, 0},
    {269, 0},
    {0, 0},
    {258, 0},
    {330, 0},
    {259, 0},
    {49, 0},
    {290, 0},
    {7, 0},
    {333, 0},
    {8, 0},
    {260, 0},
    {261, 0},
    {332, 0},
    {263, 0},
    {262, 0},
    {55, 0},
    {341, 0},
    {1, 0},
    {264, 0},
    {51, 0},
    {304, 0},
    {11, 0},
    {303, 0},
    {265, 0},
    {266, 0},
    {22, 0},
    {12, 0},
    {16, 0},
    {35, 0},
    {267, 0},
    {268, 0},
    {271, 0},
    {13, 0},
    {272, 0},
    {275, 0},
    {276, 0},
    {277, 0},
    {283, 0},
    {291, 0},
    {292, 0},
    {293, 0},
    {273, 0},
    {274, 0},
    {339, 0},
    {313, 0},
    {36, 0},
    {37, 0},
    {38, 0},
    {50, 0},
    {39, 0},
    {40, 0},
    {41, 0},
    {42, 0},
    {43, 0},
    {44, 0},
    {45, 0},
    {46, 0},
    {48, 0},
    {348, 0},
    {329, 0},
    {342, 0},
    {278, 0},
    {279, 0},
    {280, 0},
    {282, 0},
    {281, 0},
    {345, 0},
    {346, 0},
    {347, 0},
    {349, 0},
    {359, 0},
    {284, 0},
    {285, 0},
    {358, 0},
    {289, 0},
    {23, 0},
    {52, 0},
    {288, 0},
    {286, 0},
    {361, 0},
    {287, 0},
    {350, 0},
    {351, 0},
    {352, 0},
    {296, 0},
    {297, 0},
    {298, 0},
    {299, 0},
    {300, 0},
    {295, 0},
    {360, 0},
    {1, "elif"},
    {1, "sinosi"},
    {1, "si"},
    {1, "no"},
    {1, "else"},
    {1, "sino"},
    {357, 0},
    {364, 0},
    {344, 0},
    {365, 0},
    {362, 0},
    {302, 0},
    {1, "finally"},
    {1, "finalmente"},
    {353, 0},
    {301, 0},
    {314, 0},
    {354, 0},
    {5, 0},
    {6, 0},
    {308, 0},
    {306, 0},
    {305, 0},
    {307, 0},
    {355, 0},
    {309, 0},
    {1, "or"},
    {1, "o"},
    {310, 0},
    {1, "and"},
    {1, "y"},
    {1, "not"},
    {311, 0},
    {312, 0},
    {20, 0},
    {21, 0},
    {27, 0},
    {30, 0},
    {29, 0},
    {28, 0},
    {28, 0},
    {1, "in"},
    {1, "is"},
    {1, "en"},
    {1, "es"},
    {315, 0},
    {18, 0},
    {316, 0},
    {32, 0},
    {317, 0},
    {19, 0},
    {318, 0},
    {33, 0},
    {34, 0},
    {319, 0},
    {14, 0},
    {15, 0},
    {320, 0},
    {17, 0},
    {24, 0},
    {47, 0},
    {31, 0},
    {321, 0},
    {322, 0},
    {54, 0},
    {323, 0},
    {325, 0},
    {324, 0},
    {9, 0},
    {10, 0},
    {25, 0},
    {331, 0},
    {26, 0},
    {2, 0},
    {3, 0},
    {1, "None"},
    {1, "True"},
    {1, "False"},
    {336, 0},
    {326, 0},
    {327, 0},
    {328, 0},
    {343, 0},
    {334, 0},
    {335, 0},
    {337, 0},
    {338, 0},
    {356, 0},
    {340, 0},
    {1, "def"},
    {1, "pass"},
    {1, "pasa"},
    {1, "class"},
    {1, "clase"},
    {1, "for"},
    {1, "por"},
    {1, "break"},
    {1, "rompe"},
    {1, "continue"},
    {1, "continua"},
    {1, "return"},
    {1, "regresa"},
    {1, "del"},
    {1, "borra"},
    {1, "raise"},
    {1, "lanza"},
    {1, "global"},
    {1, "nonlocal"},
    {1, "nolocal"},
    {1, "assert"},
    {1, "asevera"},
    {1, "with"},
    {1, "usando"},
    {1, "except"},
    {1, "excepto"},
    {1, "lambda"},
    {1, "yield"},
    {1, "genera"},
    {1, "while"},
    {1, "mientras"},
    {1, "import"},
    {1, "importa"},
    {1, "from"},
    {1, "desde"},
    {1, "if"},
    {1, "as"},
    {1, "como"},
    {1, "try"},
    {1, "intenta"},
    {363, 0},
};
grammar _PyParser_Grammar = {
    110,
    dfas,
    {227, labels},
    256
};
